version: '2'
services:

  ## Config Servers
  config01:
    image: mongo
    command: mongod --auth --port 27017 --configsvr --replSet configserver  --oplogSize 16 --keyFile /etc/mongo/mongodb.key
    volumes:
      - ./scripts:/scripts
      - /home/emp-03/mongo:/etc/mongo
  config02:
    image: mongo
    command: mongod --auth --port 27017 --configsvr --replSet configserver  --oplogSize 16 --keyFile /etc/mongo/mongodb.key
    volumes:
      - ./scripts:/scripts
      - /home/emp-03/mongo:/etc/mongo
  config03:
    image: mongo
    command: mongod --auth --port 27017 --configsvr --replSet configserver  --oplogSize 16 --keyFile /etc/mongo/mongodb.key
    volumes:
      - ./scripts:/scripts
      - /home/emp-03/mongo:/etc/mongo

  ## Shards
  shard01a:
    image: mongo
    command: mongod --auth --port 27018 --shardsvr --replSet shard01  --oplogSize 16 --keyFile /etc/mongo/mongodb.key
    volumes:
      - ./scripts:/scripts
      - /home/emp-03/mongo:/etc/mongo
  shard01b:
    image: mongo
    command: mongod --auth --port 27018 --shardsvr --replSet shard01  --oplogSize 16 --keyFile /etc/mongo/mongodb.key
    volumes:
      - ./scripts:/scripts
      - /home/emp-03/mongo:/etc/mongo
  shard02a:
    image: mongo
    command: mongod --auth --port 27019 --shardsvr --replSet shard02  --oplogSize 16 --keyFile /etc/mongo/mongodb.key
    volumes:
      - ./scripts:/scripts
      - /home/emp-03/mongo:/etc/mongo
  shard02b:
    image: mongo
    command: mongod --auth --port 27019 --shardsvr --replSet shard02  --oplogSize 16 --keyFile /etc/mongo/mongodb.key
    volumes:
      - ./scripts:/scripts
      - /home/emp-03/mongo:/etc/mongo
  shard03a:
    image: mongo
    command: mongod --auth --port 27020 --shardsvr --replSet shard03  --oplogSize 16 --keyFile /etc/mongo/mongodb.key
    volumes:
      - ./scripts:/scripts
      - /home/emp-03/mongo:/etc/mongo
  shard03b:
    image: mongo
    command: mongod --auth --port 27020 --shardsvr --replSet shard03  --oplogSize 16 --keyFile /etc/mongo/mongodb.key
    volumes:
      - ./scripts:/scripts
      - /home/emp-03/mongo:/etc/mongo

  ## Router
  router:
    image: mongo
    command: mongos --port 27017 --configdb configserver/config01:27017,config02:27017,config03:27017 --bind_ip_all --keyFile /etc/mongo/mongodb.key
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/scripts
      - /home/emp-03/mongo:/etc/mongo
    depends_on:
      - config01
      - config02
      - config03
      - shard01a
      - shard01b
      - shard02a
      - shard02b
      - shard03a
      - shard03b
